import pygame

# Events for Server
SERVER_CONNECTED_EVENT = pygame.USEREVENT + 1
SERVER_DISCONNECTED_EVENT = pygame.USEREVENT + 2
SERVER_MESSAGE_RECEIVED_EVENT = pygame.USEREVENT + 3

# Events for Client
CLIENT_CONNECTED_EVENT = pygame.USEREVENT + 4
CLIENT_DISCONNECTED_EVENT = pygame.USEREVENT + 5
CLIENT_MESSAGE_RECEIVED_EVENT = pygame.USEREVENT + 6
