"""Events for the Clue-Less Application"""

import pygame

# Events for Server
SERVER_COULD_NOT_START_EVENT = pygame.USEREVENT + 1
SERVER_CONNECTED_EVENT = pygame.USEREVENT + 2
SERVER_DISCONNECTED_EVENT = pygame.USEREVENT + 3
SERVER_MESSAGE_RECEIVED_EVENT = pygame.USEREVENT + 4

# Events for Client
CLIENT_COULD_NOT_CONNECT_EVENT = pygame.USEREVENT + 5
CLIENT_CONNECTED_EVENT = pygame.USEREVENT + 6
CLIENT_DISCONNECTED_EVENT = pygame.USEREVENT + 7
CLIENT_MESSAGE_RECEIVED_EVENT = pygame.USEREVENT + 8
