import pygame

# Events for Server
CLIENT_CONNECTED_EVENT = pygame.USEREVENT + 1
CLIENT_MESSAGE_RECEIVED_EVENT = pygame.USEREVENT + 2
CLIENT_DISCONNECTED_EVENT = pygame.USEREVENT + 3

# Events for Client
SERVER_CONNECTED_EVENT = pygame.USEREVENT + 4
SERVER_MESSAGE_RECEIVED_EVENT = pygame.USEREVENT + 5
SERVER_DISCONNECTED_EVENT = pygame.USEREVENT + 6
